services:
  # 1. Offline Store (PostgreSQL + PostGIS)
  db:
    image: postgis/postgis:16-3.4
    container_name: routematch_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=routematch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  # 2. Online Store (Redis)
  redis:
    image: redis:7-alpine
    container_name: routematch_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 3. Redis GUI (RedisInsight)
  redisinsight:
    image: redis/redisinsight:latest
    container_name: routematch_redis_gui
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/data
  # 4. Monitoring Stack (Prometheus + Grafana)
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows access to your python script on localhost

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  # 5. The ML Model API (Brain)
  model-api:
    build: .  # Uses the Dockerfile in current dir
    container_name: routematch_model
    command: uvicorn app.model:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models # Mount models so we don't need to rebuild to update weights
    depends_on:
      - redis

  # 6. The Dispatch Orchestrator (Client API)
  dispatch-service:
    build: . # Uses the SAME Dockerfile
    container_name: routematch_dispatcher
    command: uvicorn app.client:app --host 0.0.0.0 --port 9000
    ports:
      - "9000:9000"
    environment:
      # Use the docker service name 'model-api', not localhost
      - MODEL_API_URL=http://model-api:8000/predict/batch
      - REDIS_HOST=redis
    depends_on:
      - model-api
      - redis

volumes:
  postgres_data:
  redis_data:
  redisinsight_data: